### ISSUE TITLE
Support double quotes ("") and other special characters, potential fix included

### ISSUE THREAD

**Issue by pe224** [nwjlyons/google-search#7]
The plugin breaks when given search strings including quote characters, e.g.
`search this "and this"`

A potential fix would be to convert the query to URL format (substituting special characters) by using `urllib` like so:
```
import webbrowser
from urllib.parse import quote_plus         # <--- added
import sublime, sublime_plugin


def search(q):
    settings = sublime.load_settings("google_search.sublime-settings")
    # Attach the suffix and the prefix
    q = quote_plus(settings.get('prefix', '') + q + settings.get('suffix', ''))    # <--- changed

    fullUrl = settings.get('domain', 'https://www.google.com') + "/search?q=%s" % q

    webbrowser.open(fullUrl)
```

**Comment by ionutvmi** [comment]
I have applied the fix.
Let me know how it works.

It should be available in package control in a few hours.

**Comment by pe224** [comment]
Looks good!

**Comment by kallookoo** [comment]
Please revert this change because quote_plus replace extra params.
e.g:
`https://www.google.com/search?q=quote_plus%26name%3Df%26gws_rd%3Dncr%2Cssl`
but correct link is
`https://www.google.com/search?q=quote_plus&name=f&gws_rd=ncr,ssl`

Thanks

**Comment by ionutvmi** [comment]
@kallookoo I have pushed the fix.
It should be available in a few hours.
