### ISSUE TITLE
webbrowser not open default browser

### ISSUE THREAD

**Issue by kallookoo** [nwjlyons/google-search#8]
Hi,
in mac os sierra, the webbrowser not open default browser.
You could add an option to select the browser to be used, such as:
```
    try:
        browser = settings.get('browser', '')
        webbrowser.get(browser).open(fullUrl)
    except:
        webbrowser.open(fullUrl)
```

thanks

Note: sublime text open url, has the same error.

**Comment by ionutvmi** [comment]
Looks ok to me, I would also include an empty check before entering the try block.

Can you create a PR for this please ?

**Comment by kallookoo** [comment]
Created Pull Request...
